import py4hw


class L1BufferInterf(py4hw.Interface):
    def __init__(self,parent,name):
        super().__init__(parent,name)

        #64 words of 32 bits each 
        self.W0 = self.addSourceToSink('W0',32)
        self.W1 = self.addSourceToSink('W1',32)
        self.W2 = self.addSourceToSink('W2',32)
        self.W3 = self.addSourceToSink('W3',32)
        self.W4 = self.addSourceToSink('W4',32)
        self.W5 = self.addSourceToSink('W5',32)
        self.W6 = self.addSourceToSink('W6',32)
        self.W7 = self.addSourceToSink('W7',32)
        self.W8 = self.addSourceToSink('W8',32)
        self.W9 = self.addSourceToSink('W9',32)
        self.W10 = self.addSourceToSink('W10',32)
        self.W11 = self.addSourceToSink('W11',32)
        self.W12 = self.addSourceToSink('W12',32)
        self.W13 = self.addSourceToSink('W13',32)
        self.W14 = self.addSourceToSink('W14',32)
        self.W15 = self.addSourceToSink('W15',32)
        self.W16 = self.addSourceToSink('W16',32)
        self.W17 = self.addSourceToSink('W17',32)
        self.W18 = self.addSourceToSink('W18',32)
        self.W19 = self.addSourceToSink('W19',32)
        self.W20 = self.addSourceToSink('W20',32)
        self.W21 = self.addSourceToSink('W21',32)
        self.W22 = self.addSourceToSink('W22',32)
        self.W23 = self.addSourceToSink('W23',32)
        self.W24 = self.addSourceToSink('W24',32)
        self.W25 = self.addSourceToSink('W25',32)
        self.W26 = self.addSourceToSink('W26',32)
        self.W27 = self.addSourceToSink('W27',32)
        self.W28 = self.addSourceToSink('W28',32)
        self.W29 = self.addSourceToSink('W29',32)
        self.W30 = self.addSourceToSink('W30',32)
        self.W31 = self.addSourceToSink('W31',32)
        self.W32 = self.addSourceToSink('W32',32)
        self.W33 = self.addSourceToSink('W33',32)
        self.W34 = self.addSourceToSink('W34',32)
        self.W35 = self.addSourceToSink('W35',32)
        self.W36 = self.addSourceToSink('W36',32)
        self.W37 = self.addSourceToSink('W37',32)
        self.W38 = self.addSourceToSink('W38',32)
        self.W39 = self.addSourceToSink('W39',32)
        self.W40 = self.addSourceToSink('W40',32)
        self.W41 = self.addSourceToSink('W41',32)
        self.W42 = self.addSourceToSink('W42',32)
        self.W43 = self.addSourceToSink('W43',32)
        self.W44 = self.addSourceToSink('W44',32)
        self.W45 = self.addSourceToSink('W45',32)
        self.W46 = self.addSourceToSink('W46',32)
        self.W47 = self.addSourceToSink('W47',32)
        self.W48 = self.addSourceToSink('W48',32)
        self.W49 = self.addSourceToSink('W49',32)
        self.W50 = self.addSourceToSink('W50',32)
        self.W51 = self.addSourceToSink('W51',32)
        self.W52 = self.addSourceToSink('W52',32)
        self.W53 = self.addSourceToSink('W53',32)
        self.W54 = self.addSourceToSink('W54',32)
        self.W55 = self.addSourceToSink('W55',32)
        self.W56 = self.addSourceToSink('W56',32)
        self.W57 = self.addSourceToSink('W57',32)
        self.W58 = self.addSourceToSink('W58',32)
        self.W59 = self.addSourceToSink('W59',32)
        self.W60 = self.addSourceToSink('W60',32)
        self.W61 = self.addSourceToSink('W61',32)
        self.W62 = self.addSourceToSink('W62',32)
        self.W63 = self.addSourceToSink('W63',32)
        self.DataReady = self.addSourceToSink('DataReady',1)
        


class FirstLayerOutputBuffer(py4hw.Logic):
    def __init__(self,parent,name,L1Connection:L1BufferInterf,output_address,output_val,values_updated):
        super().__init__(parent,name)

        self.address = self.addIn("output_address",output_address)
        self.val = self.addOut("output_val",output_val)
        self.L1 = self.addInterfaceSink("L1Connection",L1Connection)
        self.values_updated = self.addOut("values_updated",values_updated)
        self.Buffers = [0]*64

        print("FirstLayerOutputBuffer")

    
    def clock(self):

        
        add = self.address.get()
        self.val.prepare(self.Buffers[add])

        dataReady = self.L1.DataReady.get()
        self.values_updated.prepare(1 if dataReady else 0)

        if dataReady:
            print("FirstLayerBuffer:DataLoaded")
            self.Buffers[0] = self.L1.W0.get()
            self.Buffers[1] = self.L1.W1.get()
            self.Buffers[2] = self.L1.W2.get()
            self.Buffers[3] = self.L1.W3.get()
            self.Buffers[4] = self.L1.W4.get()
            self.Buffers[5] = self.L1.W5.get()
            self.Buffers[6] = self.L1.W6.get()
            self.Buffers[7] = self.L1.W7.get()
            self.Buffers[8] = self.L1.W8.get()
            self.Buffers[9] = self.L1.W9.get()
            self.Buffers[10] = self.L1.W10.get()
            self.Buffers[11] = self.L1.W11.get()
            self.Buffers[12] = self.L1.W12.get()
            self.Buffers[13] = self.L1.W13.get()
            self.Buffers[14] = self.L1.W14.get()
            self.Buffers[15] = self.L1.W15.get()
            self.Buffers[16] = self.L1.W16.get()
            self.Buffers[17] = self.L1.W17.get()
            self.Buffers[18] = self.L1.W18.get()
            self.Buffers[19] = self.L1.W19.get()
            self.Buffers[20] = self.L1.W20.get()
            self.Buffers[21] = self.L1.W21.get()
            self.Buffers[22] = self.L1.W22.get()
            self.Buffers[23] = self.L1.W23.get()
            self.Buffers[24] = self.L1.W24.get()
            self.Buffers[25] = self.L1.W25.get()
            self.Buffers[26] = self.L1.W26.get()
            self.Buffers[27] = self.L1.W27.get()
            self.Buffers[28] = self.L1.W28.get()
            self.Buffers[29] = self.L1.W29.get()
            self.Buffers[30] = self.L1.W30.get()
            self.Buffers[31] = self.L1.W31.get()
            self.Buffers[32] = self.L1.W32.get()
            self.Buffers[33] = self.L1.W33.get()
            self.Buffers[34] = self.L1.W34.get()
            self.Buffers[35] = self.L1.W35.get()
            self.Buffers[36] = self.L1.W36.get()
            self.Buffers[37] = self.L1.W37.get()
            self.Buffers[38] = self.L1.W38.get()
            self.Buffers[39] = self.L1.W39.get()
            self.Buffers[40] = self.L1.W40.get()
            self.Buffers[41] = self.L1.W41.get()
            self.Buffers[42] = self.L1.W42.get()
            self.Buffers[43] = self.L1.W43.get()
            self.Buffers[44] = self.L1.W44.get()
            self.Buffers[45] = self.L1.W45.get()
            self.Buffers[46] = self.L1.W46.get()
            self.Buffers[47] = self.L1.W47.get()
            self.Buffers[48] = self.L1.W48.get()
            self.Buffers[49] = self.L1.W49.get()
            self.Buffers[50] = self.L1.W50.get()
            self.Buffers[51] = self.L1.W51.get()
            self.Buffers[52] = self.L1.W52.get()
            self.Buffers[53] = self.L1.W53.get()
            self.Buffers[54] = self.L1.W54.get()
            self.Buffers[55] = self.L1.W55.get()
            self.Buffers[56] = self.L1.W56.get()
            self.Buffers[57] = self.L1.W57.get()
            self.Buffers[58] = self.L1.W58.get()
            self.Buffers[59] = self.L1.W59.get()
            self.Buffers[60] = self.L1.W60.get()
            self.Buffers[61] = self.L1.W61.get()
            self.Buffers[62] = self.L1.W62.get()
            self.Buffers[63] = self.L1.W63.get()


        